x-postgres-variables: &postgres-variables
#  POSTGRES_DB: "${DB__NAME}"
#  POSTGRES_USER: "${DB__USER}"
#  POSTGRES_PASSWORD: "${DB__PASSWORD}"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"


services:
  web:
    container_name: fastapi-template-web
    build:
      context: .
      dockerfile: infra/Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    container_name: fastapi-template-worker
    build:
      context: .
      dockerfile: infra/Dockerfile
    command: arq src.background.worker.WorkerSettings
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      SERVICE_NAME: WORKER
    depends_on:
      - db
      - redis

  scheduler:
    container_name: fastapi-template-scheduler
    build:
      context: .
      dockerfile: infra/Dockerfile
    command: arq src.background.scheduler.SchedulerWorkerSettings
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      SERVICE_NAME: SCHEDULER
    depends_on:
      - db
      - redis

  db:
    container_name: fastapi-template-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      <<: *postgres-variables
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U postgres -d postgres"
      timeout: 2s

  redis:
    container_name: fastapi-template-redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
