stages:
  - lint
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

ruff:
  stage: lint
  image: python:3.12-slim
  tags:
    - general-runner-docker
  script:
    - pip install ruff
    - ruff check .
  only:
    - merge_requests
    - main
    - dev
  allow_failure: false

build-image:
  stage: build
  image: docker:stable
  services:
    - docker:bind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --target prod -f infra/Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - general-runner-docker
  only:
    - main
    - dev

